services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - 4000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:${LANGFUSE_POSTGRES_PASSWORD:-1122334455}@langfuse-db:5432/langfuse_db
      - DATABASE_HOST=langfuse-db
      - DATABASE_USER=postgres
      - DATABASE_NAME=langfuse_db
      - DATABASE_PASSWORD=${LANGFUSE_POSTGRES_PASSWORD:-1122334455}
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY:-0000000000000000000000000000000000000000000000000000000000000000} # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://10.242.194.2:4000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    networks:
      - langindex-net
  langfuse-db:
    image: postgres
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${LANGFUSE_POSTGRES_PASSWORD:-1122334455}
      - POSTGRES_DB=langfuse_db
      - LANGFUSE_DB_DATA=${LANGFUSE_DB_DATA:-database_data}
    ports:
      - 5432:5432
    volumes:
      - /opt/stacks/langfuse/database_data:/var/lib/postgresql/data
    networks:
      - langindex-net
volumes:
  database_data:
    driver: local
networks:
  langindex-net: null
